branches:
  only: 
    - master

arch:
  - amd64
  - arm64

os: 
  - linux
  - osx

language: rust

rust:
  - stable
  - nightly
  - 1.46.0 # MSRV

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose
  - cargo test --all-features -- --test-threads=1
