[package]
name = "s3-server"
version = "0.1.0-dev"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/datenlord/s3-server"
readme = "README.md"
description = "S3 service implementation"
keywords = ["s3"]
categories = ["web-programming", "web-programming::http-server"]

[dependencies]
async-fs = "1.5.0"
async-trait = "0.1.40"
backtrace = "0.3.53"
base64 = "0.13.0"
chrono = "0.4.15"
const-str = { version = "0.1.2", features = ["verify-regex"] }
faster-hex = "0.4.1"
futures = "0.3.5"
hmac = "0.10.1"
httparse = "1.3.4"
hyper = "0.14.4"
md-5 = "0.9.1"
memchr = "2.3.3"
mime = "0.3.16"
nom = "6.0.0"
once_cell = "1.4.1"
path-absolutize = "3.0.6"
pin-project-lite = "0.1.7"
quick-xml = { version = "0.20.0", features = ["serialize"] }
regex = "1.3.9"
rusoto_core = "0.45.0"
rusoto_s3 = "0.45.0"
serde = "1.0.115"
serde_json = "1.0.57"
serde_urlencoded = "0.7.0"
sha2 = "0.9.1"
smallvec = "1.4.2"
thiserror = "1.0.20"
transform-stream = "0.1.2"
uuid = { version = "0.8.1", features = ["v4"] }
xml-rs = "0.8.3"

[dependencies.tracing]
git = "https://github.com/tokio-rs/tracing"
rev = "8070a85"
version = "0.2.0"
## FIXME: unpublished version

[dependencies.tracing-error]
git = "https://github.com/tokio-rs/tracing"
rev = "8070a85"
version = "0.2.0"
## FIXME: unpublished version

[dependencies.tracing-futures]
git = "https://github.com/tokio-rs/tracing"
rev = "8070a85"
version = "0.3.0"
## FIXME: unpublished version

[dev-dependencies]
anyhow = "1.0.32"
structopt = "0.3.17"

[dev-dependencies.tokio]
features = ["full"]
version = "0.2.22"
# version = "0.3.3"
## FIXME: hyper 0.13 depends on tokio 0.2
## See <https://github.com/hyperium/hyper/issues/2302> 

[dev-dependencies.tracing-subscriber]
git = "https://github.com/tokio-rs/tracing"
rev = "8070a85"
version = "0.3.0"
## FIXME: unpublished version
