[package]
name = "datenlord_s3"
version = "0.1.0"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/datenlord/datenlord_s3"
readme = "README.md"
description = "S3 service implementation for datenlord"
keywords = ["s3"]
categories = ["web"]

[features]
default = []
rt-async-std = ["async-std", "tokio"]

[dependencies]
async-std = { version = "1.6.2", optional = true }
tokio = { version = "0.2.22", optional = true }
hyper = "0.13.7"
futures = "0.3.5"
anyhow = "1.0.32"
async-trait = "0.1.36"
rusoto_s3 = "0.45.0"
rusoto_core = "0.45.0"
log = "0.4.11"
thiserror = "1.0.20"

[dev-dependencies]
datenlord_s3 = { path = ".", features = ["rt-async-std"] }
tokio = { version = "0.2.22", features = ["full"] }
async-std = { version = "1.6.2", features = ["tokio02", "attributes"] }
futures-timer = "3.0.2"
