[package]
name = "s3-server"
version = "0.1.0-dev"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/datenlord/s3-server"
readme = "README.md"
description = "S3 service implementation"
keywords = ["s3"]
categories = ["web-programming", "web-programming::http-server"]

[dependencies]
async-fs = "1.5.0"
async-trait = "0.1.40"
backtrace = "0.3.53"
base64 = "0.12.3"
bytes = "0.5.6"
chrono = "0.4.15"
const-str = { version = "0.1.2", features = ["verify-regex"] }
faster-hex = "0.4.1"
futures = "0.3.5"
hmac = "0.10.1"
httparse = "1.3.4"
hyper = "0.13.7"
md-5 = "0.9.1"
memchr = "2.3.3"
mime = "0.3.16"
nom = "5.1.2"
once_cell = "1.4.1"
path-absolutize = "3.0.6"
pin-project-lite = "0.1.7"
quick-xml = { version = "0.19.0", features = ["serialize"] }
regex = "1.3.9"
rusoto_core = "0.45.0"
rusoto_s3 = "0.45.0"
serde = "1.0.115"
serde_json = "1.0.57"
serde_urlencoded = "0.7.0"
sha2 = "0.9.1"
smallvec = "1.4.2"
thiserror = "1.0.20"
tracing = "0.1.21"
tracing-error = "0.1.2"
tracing-futures = "0.2.4"
transform-stream = "0.1.2"
uuid = { version = "0.8.1", features = ["v4"] }
xml-rs = "0.8.3"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }
async-std = { version = "1.6.3", features = ["tokio02", "attributes"] }
futures-timer = "3.0.2"
anyhow = "1.0.32"
structopt = "0.3.17"
tracing-subscriber = "0.2.12"
